package Dao;

import Model.Fundmanager;
import Model.FundmanagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundmanagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundmanager
     *
     * @mbggenerated
     */
    int countByExample(FundmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundmanager
     *
     * @mbggenerated
     */
    int deleteByExample(FundmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundmanager
     *
     * @mbggenerated
     */
    int insert(Fundmanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundmanager
     *
     * @mbggenerated
     */
    int insertSelective(Fundmanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundmanager
     *
     * @mbggenerated
     */
    List<Fundmanager> selectByExample(FundmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundmanager
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Fundmanager record, @Param("example") FundmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundmanager
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Fundmanager record, @Param("example") FundmanagerExample example);
}