package Dao;

import Model.Fxrate;
import Model.FxrateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FxrateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fxrate
     *
     * @mbggenerated
     */
    int countByExample(FxrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fxrate
     *
     * @mbggenerated
     */
    int deleteByExample(FxrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fxrate
     *
     * @mbggenerated
     */
    int insert(Fxrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fxrate
     *
     * @mbggenerated
     */
    int insertSelective(Fxrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fxrate
     *
     * @mbggenerated
     */
    List<Fxrate> selectByExample(FxrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fxrate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Fxrate record, @Param("example") FxrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fxrate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Fxrate record, @Param("example") FxrateExample example);
}