package Dao;

import Model.Information;
import Model.InformationExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InformationMapper {

   // List<Information> queryForInformation(String type, String date);



   List<Information> getInformationOfSameType(String type);
    int deleteInformation(int infoId);
    int updateInformation(Information info);
    int createInformation(Information info);
    List<Information> getInformationPeriod(@Param("type")String type, @Param("date")Date date);

    int createInformationForPrice(@Param("symbol")String symbol,@Param("type") String type,@Param("price") double price,@Param("ccy") String ccy,@Param("date") Date date);


    List<Information> getRecentPrice(@Param("symbol")String symbol,@Param("type") String type);


    List<Information> queryForInformation(String type);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int countByExample(InformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int deleteByExample(InformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int insert(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int insertSelective(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    List<Information> selectByExample(InformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Information record, @Param("example") InformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Information record, @Param("example") InformationExample example);
}