package Dao;

import Model.Portfolio;
import Model.PortfolioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PortfolioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbggenerated
     */
    int countByExample(PortfolioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbggenerated
     */
    int deleteByExample(PortfolioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbggenerated
     */
    int insert(Portfolio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbggenerated
     */
    int insertSelective(Portfolio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbggenerated
     */
    List<Portfolio> selectByExample(PortfolioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Portfolio record, @Param("example") PortfolioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolio
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Portfolio record, @Param("example") PortfolioExample example);
}