package Model;

public class Fundmanager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundmanager.id
     *
     * @mbggenerated
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundmanager.name
     *
     * @mbggenerated
     */
    private String name;

    public Fundmanager(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundmanager.id
     *
     * @return the value of fundmanager.id
     *
     * @mbggenerated
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundmanager.id
     *
     * @param id the value for fundmanager.id
     *
     * @mbggenerated
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundmanager.name
     *
     * @return the value of fundmanager.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundmanager.name
     *
     * @param name the value for fundmanager.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String toString(){
        return "name : " + this.name + " id : " + this.id;
    }
}