package Model;

import java.util.Date;

public class Information {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.id
     *
     * @mbggenerated
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.ccy
     *
     * @mbggenerated
     */
    private String ccy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.id
     *
     * @return the value of information.id
     *
     * @mbggenerated
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.id
     *
     * @param id the value for information.id
     *
     * @mbggenerated
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.symbol
     *
     * @return the value of information.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.symbol
     *
     * @param symbol the value for information.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.price
     *
     * @return the value of information.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.price
     *
     * @param price the value for information.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.type
     *
     * @return the value of information.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.type
     *
     * @param type the value for information.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.ccy
     *
     * @return the value of information.ccy
     *
     * @mbggenerated
     */
    public String getCcy() {
        return ccy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.ccy
     *
     * @param ccy the value for information.ccy
     *
     * @mbggenerated
     */
    public void setCcy(String ccy) {
        this.ccy = ccy == null ? null : ccy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.date
     *
     * @return the value of information.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.date
     *
     * @param date the value for information.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date;
    }
}