package Model;

import java.util.Date;

public class Information {
    private int id;

    private String symbol;

    private Double price;

    private String type;

    private String ccy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.date
     *
     * @mbggenerated
     */
    private Date date;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    public String getCcy() {
        return ccy;
    }

    public void setCcy(String ccy) {
        this.ccy = ccy == null ? null : ccy.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.date
     *
     * @return the value of information.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.date
     *
     * @param date the value for information.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {

        this.date = date;
    }
    public String toString(){
        return "Id : " + id + " symbol " + symbol + " type: " + type + " price: " + price;
    }
}