package Model;

import java.util.Date;

public class Position {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.id
     *
     * @mbggenerated
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.qty
     *
     * @mbggenerated
     */
    private int qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.price
     *
     * @mbggenerated
     */
    private double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.ccy
     *
     * @mbggenerated
     */
    private String ccy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.portfolioID
     *
     * @mbggenerated
     */
    private int portfolioid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.date
     *
     * @mbggenerated
     */
    private Date date;

    public Position(int id, int qty, String symbol, double price, String ccy, String type, int portfolioid, Date date) {
        this.id = id;
        this.qty = qty;
        this.symbol = symbol;
        this.price = price;
        this.ccy = ccy;
        this.type = type;
        this.portfolioid = portfolioid;
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.id
     *
     * @return the value of position.id
     *
     * @mbggenerated
     */


    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.id
     *
     * @param id the value for position.id
     *
     * @mbggenerated
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.qty
     *
     * @return the value of position.qty
     *
     * @mbggenerated
     */
    public int getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.qty
     *
     * @param qty the value for position.qty
     *
     * @mbggenerated
     */
    public void setQty(int qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.symbol
     *
     * @return the value of position.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.symbol
     *
     * @param symbol the value for position.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.price
     *
     * @return the value of position.price
     *
     * @mbggenerated
     */
    public double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.price
     *
     * @param price the value for position.price
     *
     * @mbggenerated
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.ccy
     *
     * @return the value of position.ccy
     *
     * @mbggenerated
     */
    public String getCountry() {
        return ccy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.ccy
     *
     * @param ccy the value for position.ccy
     *
     * @mbggenerated
     */
    public void setCountry(String ccy) {
        this.ccy = ccy == null ? null : ccy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.type
     *
     * @return the value of position.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.type
     *
     * @param type the value for position.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.portfolioID
     *
     * @return the value of position.portfolioID
     *
     * @mbggenerated
     */
    public int getPortfolioid() {
        return portfolioid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.portfolioID
     *
     * @param portfolioid the value for position.portfolioID
     *
     * @mbggenerated
     */
    public void setPortfolioid(int portfolioid) {
        this.portfolioid = portfolioid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.date
     *
     * @return the value of position.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.date
     *
     * @param date the value for position.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}